### ISSUE TITLE
Need to error handle parsing / file access

### ISSUE THREAD

**Issue by FreeLiveTutor** [DicaxDorcas/sessions-plus#1]
Just brought down my server....!:

``` javascript
undefined:0
^
SyntaxError: Unexpected end of input                                                                  
    at Object.parse (native)
    at Object.exports.start (/Users/danhouldsworth/work/FLTsessionApp/node_modules/websocketconference-server/node_modules/sessions-plus/sessions-plus.js:45:28)   
```

I'll aim to submit a patch later if it helps,

**Comment by DicaxDorcas** [comment]
Ah! This bug hit me earlier too. Will be investigating over the weekend, please let me know if your efforts are fruitful.

**Comment by FreeLiveTutor** [comment]
Struggling with it to be honest. 
I've had some success by splitting the readFile and Parse into two lines and error handling them separately, but I still get the occasional Unexpected End of Stream which means occasionally I'm not getting the right read of the session. Odd.

**Comment by DicaxDorcas** [comment]
It's a peculiar bug. Looked at it myself yesterday and couldn't make
much headway. 

On 22/09/2013 3:20 pm, FreeLiveTutor wrote: 

> Struggling with it to be honest. 
> I've had some success by splitting
> the readFile and Parse into two lines and error handling them
> separately, but I still get the occasional Unexpected End of Stream
> which means occasionally I'm not getting the right read of the session.
> Odd. 
> 
> On 20 Sep 2013, at 14:47, Ross Walker
> notifications@github.com wrote: 
> 
> > Ah! This bug hit me earlier
> > too. Will be investigating over the weekend, please let me know if your
> > efforts are fruitful. 
> > 
> > ## 
> > 
> > Reply to this email directly or
> > view it on GitHub. 
> 
> ## 
> 
> Reply to this email directly or view it on
> GitHub [1].

## Links:

[1]
https://github.com/DicaxDorcas/sessions-plus/issues/1#issuecomment-24882923

**Comment by FreeLiveTutor** [comment]
Are you able to replicate it?

For me it occurs about once for the ten requests made on launch of the flt.io app

**Comment by DicaxDorcas** [comment]
I get it rarely in my test environment. I think it may be due to
writing/reading lock of some sort. 

On 22/09/2013 6:50 pm,
FreeLiveTutor wrote: 

> Are you able to replicate it? 
> 
> For me it
> occurs about once for the ten requests made on launch of the flt.io app
> 
> > On 22 Sep 2013, at 17:07, Ross Walker notifications@github.com
> > wrote: 
> > 
> > It's a peculiar bug. Looked at it myself
> > yesterday and couldn't make 
> > much headway. 
> > 
> > On 22/09/2013
> > 3:20 pm, FreeLiveTutor wrote: 
> > 
> > > Struggling with it to be
> > > honest. 
> > > I've had some success by splitting 
> > > the readFile and
> > > Parse into two lines and error handling them 
> > > separately, but I
> > > still get the occasional Unexpected End of Stream 
> > > which means
> > > occasionally I'm not getting the right read of the session. 
> > > Odd. 
> > > 
> > > On 20 Sep 2013, at 14:47, Ross Walker 
> > 
> > notifications@github.com wrote: 
> > 
> > > > Ah! This bug hit me
> > > > earlier 
> > > > too. Will be investigating over the weekend, please let me
> > > > know if your 
> > > > efforts are fruitful. 
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or 
> > > > view it on GitHub. 
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on 
> > > GitHub [1]. 
> > 
> > ## Links: 
> > 
> > [1] 
> > 
> > https://github.com/DicaxDorcas/sessions-plus/issues/1#issuecomment-24882923
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/DicaxDorcas/sessions-plus/issues/1#issuecomment-24886737

**Comment by FreeLiveTutor** [comment]
Am much clearer on this now.

``` javascript
foo=""
JSON.parse(foo)
```

will always return the witnessed `Unexpected end of input` error.
The issue is that the readFile is returning an empty string "" due to the race conditions.

**Comment by DicaxDorcas** [comment]
Ah! That explains it.
